# This is a basic workflow to help you get started with Actions

name: GitActions-Demo2

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  GitActions-demo-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo "job.triggered.event is ${{ github.event_name }}"
      - run: echo "job.running.os.is ${{ runner.os }}"
      - run: echo "job.branch is ${{ github.ref }}" 
      - run: echo "job.repo is ${{ github.repository }}"
      - run: echo "job.status is ${{ job.status }}"
      - name: Check out repo code
        uses: actions/checkout@v2
      - name: List files on repository
        run: |
         ls ${{ github.workspace }}
